In [15]:
import sqlite3
import pandas as pd

# Kết nối đến cơ sở dữ liệu SQLite
conn = sqlite3.connect('db.sqlite3')
cursor = conn.cursor()
# danh sách các bảng trong sqlit3
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';") 
tables = cursor.fetchall()
# Truy vấn dữ liệu từ bảng
cursor.execute("SELECT * FROM CSDLHM_loaithucvat")
rows = cursor.fetchall()

# Lấy tên các cột
column_names = [description[0] for description in cursor.description]
# Chuyển đổi dữ liệu thành DataFrame
df_CDSL_Loai = pd.DataFrame(rows, columns=column_names).dropna(subset=['Tên_Loài_Tiếng_Việt'])
# Truy vấn dữ liệu từ bảng
cursor.execute("SELECT * FROM CSDLHM_herbalmedicine")
rows = cursor.fetchall()
# Lấy tên các cột
column_names = [description[0] for description in cursor.description]
# Chuyển đổi dữ liệu thành DataFrame
df_CSDLHM_herbalmedicine = pd.DataFrame(rows, columns=column_names).dropna(subset=['Dược_liệu_Tiếng_Việt'])

In [16]:
df_CSDLHM_herbalmedicine = df_CSDLHM_herbalmedicine.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
df_CSDLHM_herbalmedicine['Dược_liệu_Tiếng_Latin_Kiểu_DĐVN'] = df_CSDLHM_herbalmedicine['Dược_liệu_Tiếng_Latin_Kiểu_DĐVN'].str.lower().str.replace(r'\s{2,}', ' ', regex=True).str.strip()
df_CSDLHM_herbalmedicine.head(3)

,page_ptr_id,Dược_liệu_Tiếng_Việt,Dược_liệu_Tiếng_Trung_Ký_tự,Dược_liệu_Tiếng_Trung_Phiên_âm,Dược_liệu_Tiếng_Anh,Dược_liệu_Tiếng_Latin,Dược_liệu_Tiếng_Latin_Kiểu_DĐVN,Dược_liệu_Tiếng_Latin_Kiểu_DĐHK,Dược_liệu_Tiếng_Latin_Kiểu_Thông_Tư,Bộ_phận_dùng_Tiếng_Việt,...,Dược_liệu_Công_Năng_Chủ_Trị_DĐVN,Tác_Dụng_Y_Dược_Cổ_Truyền,Dược_Điển_Hồng_Kông_id,Loài_id,Loài_Thay_Thế_id,AnhDuocLieu_Block,AnhSoiBot_Block,Chất_chuẩn_Block,AnhViPhau_Block,Dược_điển_Hồng_Kông_id
6,553,tô tử,紫苏子,Zi Su Zi,Perilla Fruit,None,None,None,None,None,...,"<p data-block-key=""6zdfv"">Giáng khí. tiêu đờm....",,None,420.0,NaN,[],[],[],[],131.0
8,556,Tô ngạnh,紫苏梗,Zi Su Geng,Perilla Frutescens Var. Arguta,Caulis Perillae frutescensis,caulis perillae frutescensis,None,None,Cành,...,,,None,420.0,NaN,[],[],[],[],131.0
17,565,,追凤箭,Zhui Feng Jian,~,,,,,,...,,,None,NaN,NaN,null,null,null,null,NaN

In [17]:
df_CSDL_SV = pd.read_excel('Duoc lieu.xlsx')
df_CSDL_SV = df_CSDL_SV.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
df_CSDL_SV['Tên khoa học của Dược liệu'] = df_CSDL_SV['Tên khoa học của Dược liệu'].str.lower().str.replace(r'\s{2,}', ' ', regex=True).str.strip()
df_CSDL_SV['Tên tiếng việt dược liệu'] = df_CSDL_SV['Tên tiếng việt dược liệu'].str.lower().str.replace(r'\s{2,}', ' ', regex=True).str.strip().str.title()
df_CSDL_SV.head(3)

,Đạt,Tên tiếng việt dược liệu,Tên tiếng việt của thực vật,Tên khoa học của Dược liệu,Tên khoa học của Thực vật trong dược điển Việt Nam V,Synonym,Loài thay thế 1,Loài thay thế 2,Loài thay thế 3,Tên khoa học của Thực vật theo KEW,...,Mô tả thực vật bạn sử dụng tài liệu nào,Phân bố của dược liệu trên thế giới,Phân bố tại Việt Nam,Thành phần hóa học,Biomaker DDHK,Biomarker_DDVN,Tác dụng dược lý của Dược liệu,Tính vị quy kinh,Công năng chủ trị,Dựa tên thông tin thu thập được hãy viêt một đoạn tóm tắt ngắn về dược liệu
0,NaN,Mạn Kinh Tử (Quả),"Mạn kinh tử, quan âm, kinh tử, vạn kim tử, đẹn...",fructus viticis trifoliae,Vitex trifolia L.,NaN,Vitex rotundifolia L. f.,NaN,NaN,NaN,...,"""Những cây thuốc và vị thuốc Việt Nam"" - Đỗ Tấ...","có nguồn gốc từ: Bolivia, Brazil North, Brazil...",Màn kinh tử mọc hoang rất nhiều ở khắp nơi tro...,"Tinh dầu. camphen, pinen (55%), ditecpen ancol...",NaN,NaN,- Theo tài liệu cổ: có tác dụng tán phong nhiệ...,"Khổ, tân, vi hàn. Vào kinh can, phế, bàng quan...","Sơ tán phong nhiệt, khu phong thắng thấp.\nChủ...",Dược liệu Mạn kinh tử (Fructus Viticis trifoli...
1,NaN,Măng Cụt (Vỏ Quả),"Măng cụt, Sơn Trúc Tử",pericarpium garciniae mangostanae,Garcinia mangostana L.,NaN,NaN,NaN,NaN,NaN,...,"""Những cây thuốc và vị thuốc Việt Nam"" - Đỗ Tấ...","- Native to: Borneo, Malaya\n- Introduced into...",Nguồn gốc ở các đảo La Sôngđơ và Moluyc (Malai...,"Trong vỏ quả có chứa từ 7-13% tanin, chất nhựa...",NaN,NaN,"- chữa đau bụng đi ỉa lỏng, chữa lỵ, có khi cò...","Vị chát, tính ấm. Vào kinh đại tràng.","Sát trùng chỉ lỵ, thu liễm săn da.\nChủ trị: Đ...",Dược liệu từ cây Măng cụt hay còn gọi là cây S...
2,NaN,Viễn Chí (Rễ),Viễn chí,radix polygalae,Polygala tenuifolia Wild.,NaN,Polygala sibirica L.,NaN,NaN,NaN,...,"""Những cây thuốc và vị thuốc Việt Nam"" - Đỗ Tấ...","Tập trung chủ yếu ở khu vực Âu Á, trải dài từ ...","Tại miền Bắc mới phát hiện ở Ninh Bình, Nam Đị...","(1) saponin, xanthon, oligosaccharides, terpen...",NaN,Tenuifolin,- Trừ đờm\n- Kích thích cơ của tử cung,"Khố, tân, ôn. Vào kinh tâm, thận, phế","Công năng: an thần ích trí, trừ đờm chỉ khái\n...",Rễ viễn chí(Radix Polygalae) là rễ khô của cây...

In [18]:
print(df_CSDL_SV.columns)
print(df_CSDLHM_herbalmedicine.columns)

Index(['Đạt', 'Tên tiếng việt dược liệu', 'Tên tiếng việt của thực vật',
       'Tên khoa học của Dược liệu',
       'Tên khoa học của Thực vật trong dược điển Việt Nam V', 'Synonym',
       'Loài thay thế 1', 'Loài thay thế 2', 'Loài thay thế 3',
       'Tên khoa học của Thực vật theo KEW', 'Họ thực vật ', 'Mô tả thực vật',
       'Mô tả thực vật bạn sử dụng tài liệu nào',
       'Phân bố của dược liệu trên thế giới ', 'Phân bố tại Việt Nam',
       'Thành phần hóa học', 'Biomaker DDHK', 'Biomarker_DDVN',
       'Tác dụng dược lý của Dược liệu', 'Tính vị quy kinh',
       'Công năng chủ trị',
       'Dựa tên thông tin thu thập được hãy viêt một đoạn tóm tắt ngắn về dược liệu'],
      dtype='object')
Index(['page_ptr_id', 'Dược_liệu_Tiếng_Việt', 'Dược_liệu_Tiếng_Trung_Ký_tự',
       'Dược_liệu_Tiếng_Trung_Phiên_âm', 'Dược_liệu_Tiếng_Anh',
       'Dược_liệu_Tiếng_Latin', 'Dược_liệu_Tiếng_Latin_Kiểu_DĐVN',
       'Dược_liệu_Tiếng_Latin_Kiểu_DĐHK',
       'Dược_liệu_Tiếng_Latin_Kiểu_Thông_Tư', 'Bộ_phận_dùng_Tiếng_Việt',
       'Bộ_phận_dùng_Tiếng_Anh', 'Bộ_phận_dùng_Chế_Biến_DĐVN',
       'Bộ_phận_dùng_Chế_Biến_Thông_Tư', 'Dược_liệu_Mô_tả_DĐVN',
       'Dược_liệu_Mô_tả_Thông_Tư', 'Dược_liệu_Soi_Bột_DĐVN',
       'Dược_liệu_Vi_Phẫu_DĐVN', 'Dược_liệu_Định_Tính_DĐVN',
       'Dược_liệu_Định_Lượng_DĐVN', 'Dược_liệu_Liều_dùng_DĐVN',
       'Dược_liệu_Kiêng_Kỵ_DĐVN', 'Dược_liệu_Độ_ẩm_DĐVN',
       'Dược_liệu_Bảo_Quản_DĐVN', 'Dược_liệu_Chú_Ý_DĐVN',
       'Dược_Liệu_Tác_Dụng_Quốc_tế_Usage', 'Tên_Vị_Thuốc', 'Vị_Thuốc_Tính',
       'Vị_Thuốc_Vị', 'Vị_Thuốc_Quy_Kinh', 'Vị_Thuốc_Phân_Loại_Tác_dụng',
       'Dược_liệu_Công_Năng_Chủ_Trị_DĐVN', 'Tác_Dụng_Y_Dược_Cổ_Truyền',
       'Dược_Điển_Hồng_Kông_id', 'Loài_id', 'Loài_Thay_Thế_id',
       'AnhDuocLieu_Block', 'AnhSoiBot_Block', 'Chất_chuẩn_Block',
       'AnhViPhau_Block', 'Dược_điển_Hồng_Kông_id'],
      dtype='object')

In [19]:
name0=df_CSDLHM_herbalmedicine.columns[6]
name0
name1= df_CSDL_SV.columns[3]
df_CSDL_SV.rename(columns={name1: name0}, inplace=True)
# Sử dụng merge với how='outer'
df_CSDLHM = pd.merge(df_CSDLHM_herbalmedicine, df_CSDL_SV, on=[name0], how='right')
print(df_CSDLHM.columns)

Index(['page_ptr_id', 'Dược_liệu_Tiếng_Việt', 'Dược_liệu_Tiếng_Trung_Ký_tự',
       'Dược_liệu_Tiếng_Trung_Phiên_âm', 'Dược_liệu_Tiếng_Anh',
       'Dược_liệu_Tiếng_Latin', 'Dược_liệu_Tiếng_Latin_Kiểu_DĐVN',
       'Dược_liệu_Tiếng_Latin_Kiểu_DĐHK',
       'Dược_liệu_Tiếng_Latin_Kiểu_Thông_Tư', 'Bộ_phận_dùng_Tiếng_Việt',
       'Bộ_phận_dùng_Tiếng_Anh', 'Bộ_phận_dùng_Chế_Biến_DĐVN',
       'Bộ_phận_dùng_Chế_Biến_Thông_Tư', 'Dược_liệu_Mô_tả_DĐVN',
       'Dược_liệu_Mô_tả_Thông_Tư', 'Dược_liệu_Soi_Bột_DĐVN',
       'Dược_liệu_Vi_Phẫu_DĐVN', 'Dược_liệu_Định_Tính_DĐVN',
       'Dược_liệu_Định_Lượng_DĐVN', 'Dược_liệu_Liều_dùng_DĐVN',
       'Dược_liệu_Kiêng_Kỵ_DĐVN', 'Dược_liệu_Độ_ẩm_DĐVN',
       'Dược_liệu_Bảo_Quản_DĐVN', 'Dược_liệu_Chú_Ý_DĐVN',
       'Dược_Liệu_Tác_Dụng_Quốc_tế_Usage', 'Tên_Vị_Thuốc', 'Vị_Thuốc_Tính',
       'Vị_Thuốc_Vị', 'Vị_Thuốc_Quy_Kinh', 'Vị_Thuốc_Phân_Loại_Tác_dụng',
       'Dược_liệu_Công_Năng_Chủ_Trị_DĐVN', 'Tác_Dụng_Y_Dược_Cổ_Truyền',
       'Dược_Điển_Hồng_Kông_id', 'Loài_id', 'Loài_Thay_Thế_id',
       'AnhDuocLieu_Block', 'AnhSoiBot_Block', 'Chất_chuẩn_Block',
       'AnhViPhau_Block', 'Dược_điển_Hồng_Kông_id', 'Đạt',
       'Tên tiếng việt dược liệu', 'Tên tiếng việt của thực vật',
       'Tên khoa học của Thực vật trong dược điển Việt Nam V', 'Synonym',
       'Loài thay thế 1', 'Loài thay thế 2', 'Loài thay thế 3',
       'Tên khoa học của Thực vật theo KEW', 'Họ thực vật ', 'Mô tả thực vật',
       'Mô tả thực vật bạn sử dụng tài liệu nào',
       'Phân bố của dược liệu trên thế giới ', 'Phân bố tại Việt Nam',
       'Thành phần hóa học', 'Biomaker DDHK', 'Biomarker_DDVN',
       'Tác dụng dược lý của Dược liệu', 'Tính vị quy kinh',
       'Công năng chủ trị',
       'Dựa tên thông tin thu thập được hãy viêt một đoạn tóm tắt ngắn về dược liệu'],
      dtype='object')

In [20]:
import os
import requests
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import DrawingOptions
import yaml
from pygbif import species
import requests
import json
from jsonpath_ng import jsonpath, parse
import io
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import AllChem
import folium
from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
from rdkit import rdBase
from rdkit.Chem.Draw import DrawingOptions
import base64
from io import BytesIO
from pygbif import species as species
from pygbif import occurrences as occ
from pygbif import maps
from mpl_toolkits.basemap import Basemap
from collections import defaultdict
import geopandas as gpd 
import folium
import matplotlib.pyplot as plt
import requests
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import DrawingOptions
import os
import requests
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import DrawingOptions
import os
import pandas as pd
from PIL import Image

def get_list_images(query):
    try:
        spec = species.name_backbone(query)
        KeyGIBF = str(spec['usageKey'])
        path = f"https://api.gbif.org/v1/occurrence/search?taxonKey={KeyGIBF}&mediaType=StillImage&limit=5"
        response = requests.get(path).json()
        link_image = []
        for i in response['results']:
            for j in i['media']:
                if 'identifier' in j:
                    link_image.append(j['identifier'])
        return link_image
    except KeyError:
        print(f"Không tìm thấy 'usageKey' cho {query}")
        return []

def get_gibf(query):
    try:
        spec = species.name_backbone(query)
        return spec
    except KeyError:
        print("Không tìm thấy dữ liệu cho", query)
        return {}

# Hàm để chuyển đổi dòng DataFrame thành nội dung Markdown
def convert_row_to_markdown(row, columns):
    markdown_content = ""
    for col in columns:
        markdown_content += f"### {col}\n{row[col]}\n\n"
    return markdown_content

# Hàm để tạo cấu trúc hóa học và lưu hình ảnh
import os
import requests
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import DrawingOptions
from rdkit.Chem import AllChem
from rdkit.Chem import PandasTools


import os
import requests
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import DrawingOptions
from rdkit.Chem import PandasTools

def sanitize_filename(name):
    # Thay thế các ký tự không hợp lệ bằng dấu gạch dưới
    return "".join(c if c.isalnum() or c in " ._-" else "_" for c in name)

def get_chemical_structure_2(query, path):
    # Tạo đường dẫn tới API LOTUS
    url = f"https://lotus.naturalproducts.net/api/search/simple?query={query}"
    response = requests.get(url).json()
    # Chuyển đổi danh sách thành DataFrame
    compounds_df = pd.DataFrame(response['naturalProducts'])
    # Kiểm tra cột 'smiles' có tồn tại và không phải là None
    if 'smiles' not in compounds_df.columns or compounds_df['smiles'].isnull().all():
       raise KeyError("Cột 'smiles' không tồn tại hoặc không có dữ liệu hợp lệ trong DataFrame")
    compounds_df['smiles_count']=1
    compounds_df['name (code)'] = compounds_df.apply(lambda x: f"{x['traditional_name']} ({x['lotus_id']})", axis=1)

    grouped_compounds_df = compounds_df.groupby('chemicalTaxonomyClassyfireClass').agg({ 'smiles': lambda x: list(x), 'traditional_name': list, 'lotus_id': list, 'smiles_count': 'sum', 'name (code)': list }).reset_index()
    img_paths = []

    for _, row in grouped_compounds_df.iterrows(): 
        group = row['chemicalTaxonomyClassyfireClass'] 
        sanitized_group = sanitize_filename(group) 
        img_dir = os.path.join(path, query, "chemical structure") 
        if not os.path.exists(img_dir): 
            os.makedirs(img_dir)
        smiles_list =row['smiles'] 
        chembl_mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_list if smiles]
        img_path = os.path.join(img_dir, f"{sanitized_group}.png")
        img = Draw.MolsToGridImage(chembl_mols, legends=row['lotus_id'], molsPerRow=4)
        with open(img_path, 'wb') as f: 
            f.write(img.data)
        img_paths.append(img_path)
    return compounds_df, grouped_compounds_df, img_paths
# Thông tin về phân bố trên thế giới cũng như phân bố tại việt nam 
from pygbif import species as species
from pygbif import occurrences as occ
from pygbif import maps
def get_gibf_country(query):
        spec = species.name_backbone(query)
        if 'usageKey' in spec:
                occ_search = occ.search(taxonKey = spec['usageKey'])
                occ_df = pd.DataFrame(occ_search['results'])
                occ_global = ", ".join(str(country) for country in set(occ_df['country']) if country is not None) # phân bố trên thế giới
                filtered_df = occ_df[occ_df['country'] == 'Viet Nam'] # phân bố tại việt nam
                filtered_df['stateProvince'] = filtered_df['stateProvince'].fillna('')
                stateProvince_in_VN = ", ".join(str(state) for state in set(filtered_df['stateProvince']) if state)
                if not stateProvince_in_VN: 
                        stateProvince_in_VN = "Không có ghi nhận ở Việt Nam"
                return occ_global, stateProvince_in_VN
        else:
                return "Không có kết quả phù hợp", "Không có ghi nhận ở Việt Nam"

def get_first_words(text): 
    parts = text.split(' ') 
    if len(parts) >= 2: 
        return ' '.join(parts[:2]) 
    return

In [21]:
df_CSDLHM.columns

Index(['page_ptr_id', 'Dược_liệu_Tiếng_Việt', 'Dược_liệu_Tiếng_Trung_Ký_tự',
       'Dược_liệu_Tiếng_Trung_Phiên_âm', 'Dược_liệu_Tiếng_Anh',
       'Dược_liệu_Tiếng_Latin', 'Dược_liệu_Tiếng_Latin_Kiểu_DĐVN',
       'Dược_liệu_Tiếng_Latin_Kiểu_DĐHK',
       'Dược_liệu_Tiếng_Latin_Kiểu_Thông_Tư', 'Bộ_phận_dùng_Tiếng_Việt',
       'Bộ_phận_dùng_Tiếng_Anh', 'Bộ_phận_dùng_Chế_Biến_DĐVN',
       'Bộ_phận_dùng_Chế_Biến_Thông_Tư', 'Dược_liệu_Mô_tả_DĐVN',
       'Dược_liệu_Mô_tả_Thông_Tư', 'Dược_liệu_Soi_Bột_DĐVN',
       'Dược_liệu_Vi_Phẫu_DĐVN', 'Dược_liệu_Định_Tính_DĐVN',
       'Dược_liệu_Định_Lượng_DĐVN', 'Dược_liệu_Liều_dùng_DĐVN',
       'Dược_liệu_Kiêng_Kỵ_DĐVN', 'Dược_liệu_Độ_ẩm_DĐVN',
       'Dược_liệu_Bảo_Quản_DĐVN', 'Dược_liệu_Chú_Ý_DĐVN',
       'Dược_Liệu_Tác_Dụng_Quốc_tế_Usage', 'Tên_Vị_Thuốc', 'Vị_Thuốc_Tính',
       'Vị_Thuốc_Vị', 'Vị_Thuốc_Quy_Kinh', 'Vị_Thuốc_Phân_Loại_Tác_dụng',
       'Dược_liệu_Công_Năng_Chủ_Trị_DĐVN', 'Tác_Dụng_Y_Dược_Cổ_Truyền',
       'Dược_Điển_Hồng_Kông_id', 'Loài_id', 'Loài_Thay_Thế_id',
       'AnhDuocLieu_Block', 'AnhSoiBot_Block', 'Chất_chuẩn_Block',
       'AnhViPhau_Block', 'Dược_điển_Hồng_Kông_id', 'Đạt',
       'Tên tiếng việt dược liệu', 'Tên tiếng việt của thực vật',
       'Tên khoa học của Thực vật trong dược điển Việt Nam V', 'Synonym',
       'Loài thay thế 1', 'Loài thay thế 2', 'Loài thay thế 3',
       'Tên khoa học của Thực vật theo KEW', 'Họ thực vật ', 'Mô tả thực vật',
       'Mô tả thực vật bạn sử dụng tài liệu nào',
       'Phân bố của dược liệu trên thế giới ', 'Phân bố tại Việt Nam',
       'Thành phần hóa học', 'Biomaker DDHK', 'Biomarker_DDVN',
       'Tác dụng dược lý của Dược liệu', 'Tính vị quy kinh',
       'Công năng chủ trị',
       'Dựa tên thông tin thu thập được hãy viêt một đoạn tóm tắt ngắn về dược liệu'],
      dtype='object')

In [ ]:
#### folder dược liệu 
import os
from tabulate import tabulate
# Đảm bảo thư mục 'docs' tồn tại
if not os.path.exists('docs'):
    os.makedirs('docs')
# Đường dẫn tới thư mục lưu trữ các file markdown
path = "docs/Dược liệu/"
folder= "Dược liệu"
for idx, row in df_CSDLHM.iterrows():
    # Đảm bảo đường dẫn tới thư mục hình ảnh và file Markdown
    species_dir = os.path.join(path, row['Tên tiếng việt dược liệu'])
    if not os.path.exists(species_dir):
        os.makedirs(species_dir)
    DDHK_path = os.path.join(species_dir, "DDHK")
    SoiBot_path = os.path.join(species_dir, "Soi_Bot")
    ViPhau_path = os.path.join(species_dir, "Vi_Phau")
    os.makedirs(DDHK_path, exist_ok=True)
    os.makedirs(SoiBot_path, exist_ok=True)
    os.makedirs(ViPhau_path, exist_ok=True)
    Sci_name = get_first_words(row['Tên khoa học của Thực vật trong dược điển Việt Nam V'])
    Sci_name_gibf= get_gibf_country(Sci_name)
    try:
        #img_paths = get_chemical_structure(Sci_name, species_dir)
        compound_img= get_chemical_structure_2(Sci_name, species_dir)
    except KeyError as e:
        print(f"Không thể tạo cấu trúc hóa học cho {row['Tên tiếng việt dược liệu']}: {e}")
        #img_paths = ""  # Sử dụng một hình ảnh mặc định
        compound_img=""
    # Tạo nội dung Markdown cho các hình ảnh từ thư mục `images` 
    if compound_img:
        img_paths = [os.path.relpath(img, species_dir).replace("\\", "/") for img in compound_img[2]]
        list_compound = compound_img[1]
        markdown_table = tabulate(list_compound[['chemicalTaxonomyClassyfireClass','smiles_count']], headers='keys', tablefmt='pipe')
        def get_caption(img_name, df, col1, col2):
            match = df[df[col1] == img_name]
            if not match.empty:
                return match[col2].values[0]
            return "Không tìm thấy chú thích"

        chemical_images_2 = "\n".join([
            f'''
### Nhóm {os.path.basename(img).split('.')[0]}
<figure markdown="span">
    ![{os.path.basename(img)}]({img}){{ width=100% }}
    <figcaption>Hình ảnh cấu trúc hóa học của {get_caption(os.path.basename(img).split('.')[0], list_compound, 'chemicalTaxonomyClassyfireClass', 'smiles_count')} hoạt chất thuộc nhóm {os.path.basename(img).split('.')[0]} gồm {get_caption(os.path.basename(img).split('.')[0], list_compound, 'chemicalTaxonomyClassyfireClass', 'name (code)')}.</figcaption>
</figure>
        '''.strip() for img in img_paths
        ])

        count_comp = len(compound_img[0])
        list_comp = set(compound_img[0]['traditional_name'])
        # Lọc bỏ các giá trị None trước khi thực hiện join
        list_group_comp = ", ".join(filter(None, set(compound_img[0]['chemicalTaxonomyClassyfireClass'])))
    else:
        count_comp = "Chưa có hoạt chất nào được phân lập."
        chemical_images_2 = "Không có hình ảnh nào được tạo ra"
        list_comp = "Chưa có hoạt chất nào được phân lập"
        list_group_comp = ""
        markdown_table = ""

    # Lấy danh sách hình ảnh từ API GBIF
    image_links = get_list_images(Sci_name)
    image_markdown = "\n".join([f'<img src="{link}" alt="Mô tả hình ảnh" width="100" height="100">' for link in image_links[:7]])
    alternative_species_1 = "" 
    alternative_species_2 = "" 
    alternative_species_3 = "" 
    if not pd.isna(row['Loài thay thế 1']): 
        Sci_name_1 = get_first_words(row['Loài thay thế 1'])
        spec_l = get_gibf(Sci_name_1)
        image_links_1 = get_list_images(Sci_name_1)
        image_markdown_1 = "\n".join([f'<img src="{link}" alt="Mô tả hình ảnh" width="100" height="100">' for link in image_links_1[:7]])
        alternative_species_1 = f"""
Dược liệu này cũng có thể từ loài *{row['Loài thay thế 1']}*, thông tin về phân loại thực vật loài này như sau:
!!! info "Thông tin về phân loại thực vật của *{spec_l.get('species', 'N/A')}*"
    - **kingdom:** {spec_l.get('kingdom', 'N/A')}
    - **phylum:** {spec_l.get('phylum', 'N/A')}
    - **order:** {spec_l.get('order', 'N/A')}
    - **family:** {spec_l.get('family', 'N/A')}
    - **genus:** {spec_l.get('genus', 'N/A')}
    - **species:** *{spec_l.get('species', 'N/A')}*

Hình ảnh của loài *{row['Loài thay thế 1']}*:


{image_markdown_1}

"""

    if not pd.isna(row['Loài thay thế 2']): 
        Sci_name_2 = get_first_words(row['Loài thay thế 2'])
        spec_2 = get_gibf(Sci_name_2)
        image_links_2 = get_list_images(Sci_name_2)
        image_markdown_2 = "\n".join([f'<img src="{link}" alt="Mô tả hình ảnh" width="100" height="100">' for link in image_links_2[:7]])
        alternative_species_2 = f"""
Dược liệu này cũng có thể từ loài *{row['Loài thay thế 2']}*, thông tin về phân loại thực vật loài này như sau:
!!! info "Thông tin về phân loại thực vật của *{spec_2.get('species', 'N/A')}*"
    - **kingdom:** {spec_2.get('kingdom', 'N/A')}
    - **phylum:** {spec_2.get('phylum', 'N/A')}
    - **order:** {spec_2.get('order', 'N/A')}
    - **family:** {spec_2.get('family', 'N/A')}
    - **genus:** {spec_2.get('genus', 'N/A')}
    - **species:** *{spec_2.get('species', 'N/A')}*

Hình ảnh của loài *{row['Loài thay thế 2']}*:

{image_markdown_2}

"""


    if not pd.isna(row['Loài thay thế 3']): 
        Sci_name_3 = get_first_words(row['Loài thay thế 3'])
        spec_3 = get_gibf(Sci_name_3)
        image_links_3 = get_list_images(Sci_name_3)
        image_markdown_3 = "\n".join([f'<img src="{link}" alt="Mô tả hình ảnh" width="100" height="100">' for link in image_links_3[:7]])
        alternative_species_3 = f"""
Dược liệu này cũng có thể từ loài *{row['Loài thay thế 3']}*, thông tin về phân loại thực vật loài này như sau:
!!! info "Thông tin về phân loại thực vật của *{spec_3.get('species', 'N/A')}*"
    - **kingdom:** {spec_3.get('kingdom', 'N/A')}
    - **phylum:** {spec_3.get('phylum', 'N/A')}
    - **order:** {spec_3.get('order', 'N/A')}
    - **family:** {spec_3.get('family', 'N/A')}
    - **genus:** {spec_3.get('genus', 'N/A')}
    - **species:** *{spec_3.get('species', 'N/A')}*

Hình ảnh của loài *{row['Loài thay thế 3']}*:

{image_markdown_3}

"""
    # Lấy thông tin thực vật từ API GBIF
    spec = get_gibf(Sci_name)

    markdown_content = f"""---
title: {row['Dược_liệu_Tiếng_Việt']}
description: Dược liệu {row['Tên tiếng việt dược liệu']} từ bộ phận {row['Bộ_phận_dùng_Tiếng_Việt']} từ loài *{row['Tên khoa học của Thực vật trong dược điển Việt Nam V']}
date: 2024-12-01
categories:
  - {spec.get('family', 'N/A')}
tags:
  - {spec.get('family', 'N/A')}
  - {spec.get('genus', 'N/A')}
  - {spec.get('kingdom', 'N/A')}
---
!!! abstract "Tóm tắt"
    {row['Dựa tên thông tin thu thập được hãy viêt một đoạn tóm tắt ngắn về dược liệu']}

## Thông tin về thực vật

### Đặc điểm thực vật

Dược liệu **{row['Tên tiếng việt dược liệu']}** từ bộ phận **{row['Bộ_phận_dùng_Tiếng_Việt']}** từ loài *{row['Tên khoa học của Thực vật trong dược điển Việt Nam V']}* thuộc họ {spec.get('family', 'N/A')}. {row['Mô tả thực vật']} 

!!! info "Phân loại thực vật của *{spec.get('species', 'N/A')}*"
    - **Kingdom:** {spec.get('kingdom', 'N/A')}
    - **Phylum:** {spec.get('phylum', 'N/A')}
    - **Order:** {spec.get('order', 'N/A')}
    - **Family:** {spec.get('family', 'N/A')}
    - **Genus:** {spec.get('genus', 'N/A')}
    - **Species:** *{spec.get('species', 'N/A')}*

*Tài liệu tham khảo:* {row['Mô tả thực vật bạn sử dụng tài liệu nào']}


{image_markdown} 


### Loài thay thế (Nếu có)

{alternative_species_1}

{alternative_species_2}

{alternative_species_3}



### Phân bố trên thế giới
**Từ vườn thực vật KEW: **: {row['Phân bố của dược liệu trên thế giới ']}

**Từ CSDL GIBF** {Sci_name_gibf[0]}

### Phân bố tại Việt Nam
** {row['Mô tả thực vật bạn sử dụng tài liệu nào']}**: {row['Phân bố tại Việt Nam']}

**Từ CSDL GIBF**: {Sci_name_gibf[1]}

---

## Thông tin về dược liệu 

### Định danh

!!! info "Thông tin về tên gọi của {row['Dược_liệu_Tiếng_Việt']}"
    - Dược liệu tiếng Việt: {row['Dược_liệu_Tiếng_Việt']}
    - Dược liệu tiếng Trung: {row['Dược_liệu_Tiếng_Trung_Ký_tự']} ({row['Dược_liệu_Tiếng_Trung_Phiên_âm']})
    - Dược liệu tiếng Anh: {row['Dược_liệu_Tiếng_Anh']}
    - Dược liệu latin thông dụng: {row['Dược_liệu_Tiếng_Latin']}
    - Dược liệu latin kiểu DĐVN: {row['Dược_liệu_Tiếng_Latin_Kiểu_DĐVN']}
    - Dược liệu latin kiểu DĐVN: {row['Dược_liệu_Tiếng_Latin_Kiểu_DĐHK']}
    - Dược liệu latin kiểu thông tư: {row['Dược_liệu_Tiếng_Latin_Kiểu_Thông_Tư']}
    - Bộ phận dùng: {row['Bộ_phận_dùng_Tiếng_Việt']} ({row['Bộ_phận_dùng_Tiếng_Anh']})

### Mô tả dược liệu 
- **Theo dược điển Việt nam V:** {row['Dược_liệu_Mô_tả_DĐVN']}

- **Mô tả dược liệu theo thông tư chế biến dược liệu theo phương pháp cổ truyền:** {row['Dược_liệu_Mô_tả_Thông_Tư']}

### Chế biến 

- **Chế biến theo dược điển việt nam V**: {row['Bộ_phận_dùng_Chế_Biến_DĐVN']}

- **Chế biến theo thông tư:** {row['Bộ_phận_dùng_Chế_Biến_Thông_Tư']}

--- 

## Thành phần hóa học

- Theo tài liệu của GS. Đỗ Tất Lợi:  {row['Thành phần hóa học']}
    
- Theo cơ sở dữ liệu lotus: Từ loài *{spec.get('species', 'N/A')}* đã phân lập và xác định được {count_comp} hoạt chất thuộc về các nhóm {list_group_comp}. 

{markdown_table}

{chemical_images_2}

---

## Tác dụng dược lý

Theo tài liệu {row['Mô tả thực vật bạn sử dụng tài liệu nào']}:{row['Tác dụng dược lý của Dược liệu']}

Theo tài liệu quốc tế: {row['Dược_Liệu_Tác_Dụng_Quốc_tế_Usage']}

---

## Dược điển Việt Nam V

### Soi bột:
{row['Dược_liệu_Soi_Bột_DĐVN']}
<!-- Hình ảnh soi bột sẽ được tự động chèn vào đây sau -->
### Vi phẫu:
{row['Dược_liệu_Vi_Phẫu_DĐVN']}
<!-- Hình ảnh vi phẫu sẽ được tự động chèn vào đây sau -->
### Định tính

{row['Dược_liệu_Định_Tính_DĐVN']}

### Định lượng

{row['Dược_liệu_Định_Lượng_DĐVN']}

### Thông tin khác 
- ** Độ ẩm: ** {row['Dược_liệu_Độ_ẩm_DĐVN']}

- ** Bảo quản:** {row['Dược_liệu_Bảo_Quản_DĐVN']}
## Dược điển Hồng kong

<!-- PDF sẽ được tự động chèn vào đây sau -->


---

## Y dược học cổ truyền

- **Tên vị thuốc:** {row['Tên_Vị_Thuốc']}
- **Tính vị quy kinh:** {row['Tính vị quy kinh']}
- **Công năng chủ trị:** {row['Công năng chủ trị']}
- **Chú ý:** {row['Dược_liệu_Chú_Ý_DĐVN']}
- **Kiêng kỵ:** {row['Dược_liệu_Kiêng_Kỵ_DĐVN']}

"""
    file_name = f"{row['Tên tiếng việt dược liệu']}.md"
    file_path = os.path.join(species_dir, file_name)
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(markdown_content)

    # Cập nhật mkdocs.yml


print("Hoàn thành tạo các tệp Markdown và cập nhật mkdocs.yml.")

In [22]:
df_CSDLHM.columns

Index(['page_ptr_id', 'Dược_liệu_Tiếng_Việt', 'Dược_liệu_Tiếng_Trung_Ký_tự',
       'Dược_liệu_Tiếng_Trung_Phiên_âm', 'Dược_liệu_Tiếng_Anh',
       'Dược_liệu_Tiếng_Latin', 'Dược_liệu_Tiếng_Latin_Kiểu_DĐVN',
       'Dược_liệu_Tiếng_Latin_Kiểu_DĐHK',
       'Dược_liệu_Tiếng_Latin_Kiểu_Thông_Tư', 'Bộ_phận_dùng_Tiếng_Việt',
       'Bộ_phận_dùng_Tiếng_Anh', 'Bộ_phận_dùng_Chế_Biến_DĐVN',
       'Bộ_phận_dùng_Chế_Biến_Thông_Tư', 'Dược_liệu_Mô_tả_DĐVN',
       'Dược_liệu_Mô_tả_Thông_Tư', 'Dược_liệu_Soi_Bột_DĐVN',
       'Dược_liệu_Vi_Phẫu_DĐVN', 'Dược_liệu_Định_Tính_DĐVN',
       'Dược_liệu_Định_Lượng_DĐVN', 'Dược_liệu_Liều_dùng_DĐVN',
       'Dược_liệu_Kiêng_Kỵ_DĐVN', 'Dược_liệu_Độ_ẩm_DĐVN',
       'Dược_liệu_Bảo_Quản_DĐVN', 'Dược_liệu_Chú_Ý_DĐVN',
       'Dược_Liệu_Tác_Dụng_Quốc_tế_Usage', 'Tên_Vị_Thuốc', 'Vị_Thuốc_Tính',
       'Vị_Thuốc_Vị', 'Vị_Thuốc_Quy_Kinh', 'Vị_Thuốc_Phân_Loại_Tác_dụng',
       'Dược_liệu_Công_Năng_Chủ_Trị_DĐVN', 'Tác_Dụng_Y_Dược_Cổ_Truyền',
       'Dược_Điển_Hồng_Kông_id', 'Loài_id', 'Loài_Thay_Thế_id',
       'AnhDuocLieu_Block', 'AnhSoiBot_Block', 'Chất_chuẩn_Block',
       'AnhViPhau_Block', 'Dược_điển_Hồng_Kông_id', 'Đạt',
       'Tên tiếng việt dược liệu', 'Tên tiếng việt của thực vật',
       'Tên khoa học của Thực vật trong dược điển Việt Nam V', 'Synonym',
       'Loài thay thế 1', 'Loài thay thế 2', 'Loài thay thế 3',
       'Tên khoa học của Thực vật theo KEW', 'Họ thực vật ', 'Mô tả thực vật',
       'Mô tả thực vật bạn sử dụng tài liệu nào',
       'Phân bố của dược liệu trên thế giới ', 'Phân bố tại Việt Nam',
       'Thành phần hóa học', 'Biomaker DDHK', 'Biomarker_DDVN',
       'Tác dụng dược lý của Dược liệu', 'Tính vị quy kinh',
       'Công năng chủ trị',
       'Dựa tên thông tin thu thập được hãy viêt một đoạn tóm tắt ngắn về dược liệu'],
      dtype='object')

In [ ]:
import os
import pandas as pd

def generate_index_md(path):
    # Lấy danh sách tất cả các tệp .md trong thư mục và các thư mục con
    md_files = []
    for root, dirs, files in os.walk(path):
        for file in files:
            if file.endswith('.md') and file != index_file:
                relative_path = os.path.relpath(os.path.join(root, file), path)
                md_files.append(relative_path)
                
    # Tạo DataFrame từ danh sách tệp Markdown
    data = {'title': [], 'md_file': []}
    for md_file in md_files:
        title = os.path.splitext(os.path.basename(md_file))[0]
        data['title'].append(title)
        data['md_file'].append(md_file)
        
    df = pd.DataFrame(data)
    return df

# Ví dụ sử dụng
path = '../docs/Dược liệu/'
# Tên tệp index.md

df = generate_index_md(path)

Hoàn thành tạo index.md

In [13]:
import os
import yaml

def update_mkdocs_nav(path, folder):
    mkdocs_path = 'update_mkdocs.yml'
    docs_folder = os.path.join(path, folder)
    
    # Kiểm tra và đọc tệp mkdocs.yml
    if os.path.exists(mkdocs_path):
        with open(mkdocs_path, 'r', encoding='utf-8') as file:
            mkdocs_config = yaml.load(file, Loader=yaml.FullLoader)
    else:
        mkdocs_config = {'site_name': 'My Project', 'theme': {'name': 'material'}, 'nav': []}

    # Hàm đệ quy để xây dựng cấu trúc navigation
    def build_nav(path, nav):
        for item in sorted(os.listdir(path)):
            item_path = os.path.join(path, item)
            if os.path.isdir(item_path):
                if any(fname.endswith('.md') for fname in os.listdir(item_path)):
                    build_nav(item_path, nav)
            elif item.endswith('.md'):
                relative_path = os.path.relpath(item_path, docs_folder).replace("\\", "/")
                title = os.path.splitext(item)[0]
                nav.append({title: relative_path})

    # Xây dựng cấu trúc navigation cho thư mục docs_folder
    temp_nav = []
    build_nav(docs_folder, temp_nav)
    mkdocs_config['nav'].extend(temp_nav)

    # Ghi lại cấu hình mkdocs.yml
    with open(mkdocs_path, 'w', encoding='utf-8') as file:
        yaml.dump(mkdocs_config, file, allow_unicode=True)

# Ví dụ sử dụng




path_root = '../docs'
folder = 'Dược liệu'
# Ví dụ sử dụng
update_mkdocs_nav(path_root, folder)

In [ ]:
import os
import requests
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import DrawingOptions
import yaml
from pygbif import species

# Đảm bảo thư mục 'docs' tồn tại
if not os.path.exists('docs'):
    os.makedirs('docs')

# Hàm để lấy danh sách hình ảnh từ API GBIF với kích thước cố định
def get_list_images(query):
    try:
        spec = species.name_backbone(query)
        KeyGIBF = str(spec['usageKey'])
        path = f"https://api.gbif.org/v1/occurrence/search?taxonKey={KeyGIBF}&mediaType=StillImage&limit=5"
        response = requests.get(path).json()
        link_image = []
        for i in response['results']:
            for j in i['media']:
                if 'identifier' in j:
                    link_image.append(j['identifier'])
        return link_image
    except KeyError:
        print(f"Không tìm thấy 'usageKey' cho {query}")
        return []

def get_gibf(query):
    try:
        spec = species.name_backbone(query)
        return spec
    except KeyError:
        print("Không tìm thấy dữ liệu cho", query)
        return {}

# Hàm để chuyển đổi dòng DataFrame thành nội dung Markdown
def convert_row_to_markdown(row, columns):
    markdown_content = ""
    for col in columns:
        markdown_content += f"### {col}\n{row[col]}\n\n"
    return markdown_content

# Hàm để tạo cấu trúc hóa học và lưu hình ảnh
def get_chemical_structure(query, path):
    # Tạo đường dẫn tới API LOTUS
    url = f"https://lotus.naturalproducts.net/api/search/simple?query={query}"
    response = requests.get(url).json()
    compounds = []
    for i in response['naturalProducts']:
        lotus_id = str(i.get('lotus_id', ''))
        smiles = i.get('smiles', None)  # Sử dụng None làm giá trị mặc định nếu smiles không tồn tại
        group = i.get('chemicalTaxonomyNPclassifierSuperclass', '')
        traditional_name = i.get('traditional_name', '')
        path_lotus = f'https://lotus.naturalproducts.net/compound/lotus_id/{lotus_id}'
        compounds.append({
            'lotus_id': lotus_id,
            'smiles': smiles,
            'traditional_name': traditional_name,
            'group': group,
            'path_lotus': path_lotus
        })

    # Chuyển đổi danh sách thành DataFrame
    compounds_df = pd.DataFrame(compounds)

    # Kiểm tra cột 'smiles' có tồn tại và không phải là None
    if 'smiles' not in compounds_df.columns or compounds_df['smiles'].isnull().all():
        raise KeyError("Cột 'smiles' không tồn tại hoặc không có dữ liệu hợp lệ trong DataFrame")

    # Thiết lập style vẽ ACS 1996
    DrawingOptions.atomLabelFontSize = 1.0
    DrawingOptions.dotsPerAngstrom = 100
    DrawingOptions.bondLineWidth = 2

    # Chuyển đổi SMILES thành phân tử
    mols = [Chem.MolFromSmiles(smiles) for smiles in compounds_df['smiles'].dropna()]
    img = Draw.MolsToGridImage(mols, molsPerRow=4, subImgSize=(200, 200), legends=[name for name in compounds_df['lotus_id'].dropna()])

    # Tạo đường dẫn lưu ảnh
    img_dir = os.path.join(path, "images")
    if not os.path.exists(img_dir):
        os.makedirs(img_dir)
    img_path = os.path.join(img_dir, f"{query}-compounds.png")
    img_path_link = os.path.join("images", f"{query}-compounds.png")
    
    # Lưu hình ảnh trực tiếp từ đối tượng RDKit
    with open(img_path, 'wb') as f:
        f.write(img.data)

    return img_path_link

# Hàm để cập nhật file mkdocs.yml
def update_mkdocs_nav(title, file_path):
    mkdocs_path = 'mkdocs.yml'

    if os.path.exists(mkdocs_path):
        with open(mkdocs_path, 'r', encoding='utf-8') as file:
            mkdocs_config = yaml.load(file, Loader=yaml.FullLoader)
    else:
        mkdocs_config = {'site_name': 'My Project', 'theme': {'name': 'material'}, 'nav': []}

    # Tìm mục 'Dược liệu' trong navigation, nếu không có thì tạo mới
    duoclieu_nav = next((item for item in mkdocs_config['nav'] if 'Dược liệu' in item), None)
    if not duoclieu_nav:
        duoclieu_nav = {'Dược liệu': []}
        mkdocs_config['nav'].append(duoclieu_nav)

    # Thêm mục mới vào 'Dược liệu'
    duoclieu_nav['Dược liệu'].append({title: file_path})

    with open(mkdocs_path, 'w', encoding='utf-8') as file:
        yaml.dump(mkdocs_config, file, allow_unicode=True)

# Tạo các tệp Markdown và cập nhật mkdocs.yml cho mỗi dòng
path = "docs/Dược liệu/"
folder_TV= "Thực vật"
for idx, row in df_CDSL_Loai.iterrows():
    # Đảm bảo đường dẫn tới thư mục hình ảnh và file Markdown
    species_dir = os.path.join(path, row['Tên_Loài_Tiếng_Việt'])
    if not os.path.exists(species_dir):
        os.makedirs(species_dir)

    try:
        img_path = get_chemical_structure(row['Tên_Loài_Tiếng_Latin'], species_dir)
    except KeyError as e:
        print(f"Không thể tạo cấu trúc hóa học cho {row['Tên_Loài_Tiếng_Việt']}: {e}")
        img_path = ""  # Sử dụng một hình ảnh mặc định

    # Lấy danh sách hình ảnh từ API GBIF
    image_links = get_list_images(row['Tên_Loài_Tiếng_Latin'])
    image_markdown = "\n".join([f'<img src="{link}" alt="Mô tả hình ảnh" width="100" height="100">' for link in image_links])

    # Lấy thông tin thực vật từ API GBIF
    spec = get_gibf(row['Tên_Loài_Tiếng_Latin'])

    markdown_content = f"""---
title: {row['Tên_Loài_Tiếng_Việt']}
description: Tên khoa học là *{row['Tên_Loài_Tiếng_Latin']}* thuộc họ {spec.get('family', 'N/A')}
date: 2024-12-01
categories:
  - Thực vật
tags:
  - Thực vật
  - Loài thực vật
  - Phân bố trên thế giới
---

### Thông tin về thực vật
**Mã IPNI:** {spec.get('usageKey', 'N/A')}

**Mã WFO:** {row['Mã_Code_WFO']}

**Tên khoa học:** *{row['Tên_Loài_Tiếng_Latin']}*

**Tên khác tiếng Việt:** {row['Tên_Loài_Khác_Tiếng_Việt']}

Thông tin về phân loại thực vật từ website GIBF cho thấy tên khoa học của loài *{spec.get('scientificName', 'N/A')}* ở trạng thái {spec.get('status', 'N/A')}. Phân loại thực vật của loài được trình bầy như dưới đây
>
> - **kingdom:** {spec.get('kingdom', 'N/A')}
> - **phylum:** {spec.get('phylum', 'N/A')}
> - **order:** {spec.get('order', 'N/A')}
> - **family:** {spec.get('family', 'N/A')}
> - **genus:** {spec.get('genus', 'N/A')}
> - **species:** *{spec.get('species', 'N/A')}*
>
### Mô tả đặc điểm thực vật
{row['Mô_tả_Thực_vật']}
{image_markdown}
### Phân bố trên thế giới
{row['Phân_bố_trên_thế_giới']}

### Phân bố tại Việt Nam
{row['Phân_bố_tại_Việt_Nam']}

### Cấu trúc hóa học
![Mô tả hình ảnh]({img_path})
"""
    file_name = f"{row['Tên_Loài_Tiếng_Việt']}.md"
    file_path = os.path.join(species_dir, file_name)
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(markdown_content)

    # Cập nhật mkdocs.yml
    update_mkdocs_nav(row['Tên_Loài_Tiếng_Việt'], os.path.relpath(file_path, 'docs'), folder_TV)

print("Hoàn thành tạo các tệp Markdown và cập nhật mkdocs.yml.")

In [106]:
def get_gibf_country(Query):
    spec = species.name_backbone(Query)
    name_lookup = species.name_lookup(Query)
    df_name_lookup = pd.DataFrame(name_lookup['results'])
    occ_global = occ.search(taxonKey = spec['usageKey'])
    df_occ_global= pd.DataFrame(occ_global['results'])

    distributions= species.name_usage(key=spec['usageKey'], data='distributions')
    df_distributions = pd.DataFrame(distributions['results'])

    return spec, df_name_lookup, df_distributions, df_occ_global

In [107]:
gibf = get_gibf_country(df_CDSL_Loai['Tên_Loài_Tiếng_Latin'][59])

In [114]:
print(gibf[1].columns)
gibf[1]['synonym']

Index(['key', 'datasetKey', 'nubKey', 'parentKey', 'parent', 'kingdom',
       'phylum', 'order', 'family', 'genus', 'species', 'kingdomKey',
       'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey',
       'speciesKey', 'scientificName', 'canonicalName', 'nameType',
       'taxonomicStatus', 'rank', 'origin', 'numDescendants', 'numOccurrences',
       'taxonID', 'habitats', 'nomenclaturalStatus', 'threatStatuses',
       'descriptions', 'vernacularNames', 'higherClassificationMap', 'synonym',
       'class', 'constituentKey', 'acceptedKey', 'accepted', 'publishedIn',
       'nameKey', 'authorship', 'accordingTo', 'basionymKey', 'basionym',
       'extinct'],
      dtype='object')

0     False
1      True
2     False
3     False
4     False
      ...
89     True
90     True
91     True
92     True
93     True
Name: synonym, Length: 94, dtype: bool

In [62]:
df

,taxonKey,locationId,source,sourceTaxonKey,locality,status,country,establishmentMeans,temporal
0,3085196,CO:19450,Lista de especies de plantas presentes en ecos...,202599505,NaN,NaN,NaN,NaN,NaN
1,3085196,NaN,Integrated Taxonomic Information System (ITIS),102264290,North America,PRESENT,NaN,NaN,NaN
2,3085196,Armenia,Global Register of Introduced and Invasive Spe...,160947869,NaN,NaN,AM,INTRODUCED,NaN
3,3085196,ISO_3166-2:BE,Manual of the Alien Plants of Belgium,168400514,Belgium,PRESENT,BE,INTRODUCED,2019
4,3085196,ISO_3166-2:BE-WAL,Manual of the Alien Plants of Belgium,168400514,Walloon Region,PRESENT,BE,INTRODUCED,2019
5,3085196,ISO_3166:BE,Global Register of Introduced and Invasive Spe...,182135058,Belgium,PRESENT,BE,INTRODUCED,2019/2019
6,3085196,ISO_3166:BE-WAL,Global Register of Introduced and Invasive Spe...,182135058,Walloon Region,PRESENT,BE,INTRODUCED,2019/2019
7,3085196,ISO_3166-2:BE,Waarnemingen.be / observations.be - List of sp...,206103698,Belgium,PRESENT,BE,INTRODUCED,2019-09-11/2023-09-25
8,3085196,ISO_3166-2:BE-VLG,Waarnemingen.be / observations.be - List of sp...,206103698,Flemish Region,PRESENT,BE,INTRODUCED,2023-09-25/2023-09-25
9,3085196,ISO_3166-2:BE-WAL,Waarnemingen.be / observations.be - List of sp...,206103698,Walloon Region,PRESENT,BE,INTRODUCED,2019-09-11/2019-09-11
10,3085196,Estonia,Global Register of Introduced and Invasive Spe...,160880943,NaN,NaN,EE,INTRODUCED,NaN
11,3085196,Japan,Global Register of Introduced and Invasive Spe...,177019371,NaN,NaN,JP,INTRODUCED,NaN
12,3085196,NaN,The National Checklist of Taiwan (Catalogue of...,237321472,NaN,NaN,TW,INTRODUCED,NaN